name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull nongdev/cicd-pipeline_v2:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline_v2-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8081:8081 --name cicd-pipeline_v2-container nongdev/cicd-pipeline_v2
