name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u $DOCKER_USERNAME --password-stdin
      
    - name: Build the Docker image
      run: docker build -t nongdev/cicd-pipeline_v2 .
    - name: Push to Dockerhub
      run: docker push nongdev/cicd-pipeline_v2:latest
